version: "3.0"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9001

  database:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
